#GitHub Actionsで表示される文字列
name: Deploy to Azure Web App

#実行されるタイミング（mainブランチにpushされたとき）
on:
  push:
    branches:
      - main

#実行される処理
jobs:
  build-and-deploy:
    #実行されるVM
    runs-on: ubuntu-latest
    #各処理について
    steps:
      #VMにコードをクローン
      - uses: actions/checkout@v4

      #Node.js v20のインストール
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      #npmをインストール
      - name: Install dependencies
        run: npm install

      #package.json内に該当する記載があれば実行
      - name: Build (if exists)
        run: npm run build --if-present

      #AzureAppServiceにデプロイ
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: task-1-AppService
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
